# Google Cloud Build Configuration
# This file defines the CI/CD pipeline for building, testing, and deploying the application.
# Supports both staging and production environments via substitution variables.
#
# All environment-specific values are now passed via substitutions from the caller.
# No hardcoded project IDs or service account emails.

steps:
  # 1. Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend'
    args:
      - 'build'
      - '-t'
      - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/backend:latest'
      - '-f'
      - 'Dockerfile.backend'
      - '.'
    waitFor: ['-']

  # 2. Build the frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Frontend'
    args:
      - 'build'
      - '-t'
      - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/frontend:latest'
      # Pass the public API URL as a build argument for the frontend
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - '-f'
      - 'Dockerfile.frontend'
      - '.'
    waitFor: ['-']

  # 3. Push the backend image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Backend'
    args:
      - 'push'
      - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/backend:latest'
    waitFor: ['Build Backend']

  # 4. Push the frontend image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Frontend'
    args:
      - 'push'
      - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/frontend:latest'
    waitFor: ['Build Frontend']

  # 5. Deploy Backend to Cloud Run (migration will run on startup)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Backend'
    entrypoint: bash
    args:
      - '-c'
      - |
          set -euo pipefail

          # Clear any default gcloud service account settings to ensure explicit specification is used
          echo "ðŸ”§ Clearing default gcloud service account configuration..."
          gcloud config unset run/service-account 2>/dev/null || true

          EXTRA_FLAGS=()
          if [[ -n "${_BACKEND_DEPLOY_FLAGS}" ]]; then
            # _BACKEND_DEPLOY_FLAGS may contain multiple flags separated by spaces.
            read -r -a EXTRA_FLAGS <<< "${_BACKEND_DEPLOY_FLAGS}"
          fi

          # Debug output to verify correct service account and secrets are being used
          echo "ðŸ“‹ Deployment Configuration:"
          echo "  Environment: ${_ENVIRONMENT}"
          echo "  Service Name: ${_BACKEND_SERVICE_NAME}"
          echo "  Service Account Email: ${_BACKEND_SERVICE_ACCOUNT}"
          echo "  Cloud SQL Connection: ${_CLOUD_SQL_CONNECTION_NAME}"
          echo ""
          echo "ðŸ” Secrets Configuration:"
          echo "  DATABASE_URL: ${_DATABASE_URL_SECRET_NAME}:${_DATABASE_URL_SECRET_VERSION}"
          echo "  JWT_SECRET: ${_JWT_SECRET_NAME}:${_JWT_SECRET_VERSION}"
          echo "  JWT_REFRESH_SECRET: ${_JWT_REFRESH_SECRET_NAME}:${_JWT_REFRESH_SECRET_VERSION}"
          echo "  CSRF_TOKEN_SECRET: ${_CSRF_TOKEN_SECRET_NAME}:${_CSRF_TOKEN_SECRET_VERSION}"
          echo "  RESEND_API_KEY: ${_RESEND_API_KEY_SECRET_NAME}:${_RESEND_API_KEY_SECRET_VERSION}"

          # CORS_ORIGINã®ãƒ‘ã‚¤ãƒ—æ–‡å­—(|)ã‚’ã‚«ãƒ³ãƒž(,)ã«å¤‰æ›
          # gcloud --substitutionsã§ã¯å€¤ã«ã‚«ãƒ³ãƒžã‚’å«ã‚ã‚‰ã‚Œãªã„ãŸã‚ã€ãƒ¯ãƒ¼ã‚¯ãƒ•ãƒ­ãƒ¼å´ã§ãƒ‘ã‚¤ãƒ—æ–‡å­—ã‚’ä½¿ç”¨
          _CORS_ORIGIN_FINAL=$(echo "${_CORS_ORIGIN}" | sed 's/|/,/g')

          # Deploy with the service account passed from substitutions
          gcloud run deploy "${_BACKEND_SERVICE_NAME}" \
            --image "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/backend:latest" \
            --region "${_LOCATION}" \
            --platform managed \
            --execution-environment=gen2 \
            --service-account "${_BACKEND_SERVICE_ACCOUNT}" \
            --allow-unauthenticated \
            --set-secrets "DATABASE_URL=${_DATABASE_URL_SECRET_NAME}:${_DATABASE_URL_SECRET_VERSION},JWT_SECRET=${_JWT_SECRET_NAME}:${_JWT_SECRET_VERSION},JWT_REFRESH_SECRET=${_JWT_REFRESH_SECRET_NAME}:${_JWT_REFRESH_SECRET_VERSION},CSRF_TOKEN_SECRET=${_CSRF_TOKEN_SECRET_NAME}:${_CSRF_TOKEN_SECRET_VERSION},RESEND_API_KEY=${_RESEND_API_KEY_SECRET_NAME}:${_RESEND_API_KEY_SECRET_VERSION}" \
            --set-env-vars "NODE_ENV=${_ENVIRONMENT},CORS_ORIGIN=${_CORS_ORIGIN_FINAL},INSTANCE_CONNECTION_NAME=${_CLOUD_SQL_CONNECTION_NAME},EMAIL_FROM=${_EMAIL_FROM},EMAIL_FROM_NAME=${_EMAIL_FROM_NAME}" \
            --add-cloudsql-instances "${_CLOUD_SQL_CONNECTION_NAME}" \
            --concurrency 20 \
            --max-instances 3 \
            --min-instances 0 \
            --memory 512Mi \
            --cpu 1 \
            --cpu-boost \
            --timeout 300 \
            --port 8080 \
            --startup-probe=failureThreshold=30,timeoutSeconds=5,periodSeconds=10,httpGet.port=8080,httpGet.path=/health \
            "${EXTRA_FLAGS[@]}"
    waitFor: ['Push Backend']

  # 6. Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Frontend'
    entrypoint: bash
    args:
      - '-c'
      - |
          set -euo pipefail

          # Clear any default gcloud service account settings to ensure explicit specification is used
          echo "ðŸ”§ Clearing default gcloud service account configuration..."
          gcloud config unset run/service-account 2>/dev/null || true

          EXTRA_FLAGS=()
          if [[ -n "${_FRONTEND_DEPLOY_FLAGS}" ]]; then
            read -r -a EXTRA_FLAGS <<< "${_FRONTEND_DEPLOY_FLAGS}"
          fi

          # Debug output to verify correct service account is being used
          echo "ðŸ“‹ Deployment Configuration:"
          echo "  Environment: ${_ENVIRONMENT}"
          echo "  Service Name: ${_FRONTEND_SERVICE_NAME}"
          echo "  Service Account Email: ${_FRONTEND_SERVICE_ACCOUNT}"
          echo "  API URL: ${_NEXT_PUBLIC_API_URL}"

          # Deploy with the service account passed from substitutions
          gcloud run deploy "${_FRONTEND_SERVICE_NAME}" \
            --image "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/frontend:latest" \
            --region "${_LOCATION}" \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars "NODE_ENV=${_ENVIRONMENT},NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}" \
            --execution-environment=gen2 \
            --service-account "${_FRONTEND_SERVICE_ACCOUNT}" \
            --concurrency 50 \
            --cpu-boost \
            "${EXTRA_FLAGS[@]}"
    waitFor: ['Push Frontend']

# Define images to be pushed to Artifact Registry
images:
  - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/backend:latest'
  - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/frontend:latest'

# Define substitution variables that can be passed at build time
# All values with defaults are for local testing only.
# In CI/CD pipelines, all values should be explicitly provided.
substitutions:
  # Common settings
  _LOCATION: 'asia-northeast1' # Tokyo region
  _REPO_NAME: 'mycats-pro'
  _ENVIRONMENT: 'production'
  
  # Service names (must be provided by caller)
  _BACKEND_SERVICE_NAME: ''
  _FRONTEND_SERVICE_NAME: ''
  
  # URLs (must be provided by caller)
  _NEXT_PUBLIC_API_URL: ''
  _CORS_ORIGIN: ''
  
  # Cloud SQL connection (must be provided by caller)
  # Format: PROJECT_ID:REGION:INSTANCE_NAME
  _CLOUD_SQL_CONNECTION_NAME: ''
  
  # Service accounts (must be provided by caller)
  # Format: SERVICE_ACCOUNT_NAME@PROJECT_ID.iam.gserviceaccount.com
  _BACKEND_SERVICE_ACCOUNT: ''
  _FRONTEND_SERVICE_ACCOUNT: ''
  
  # Secret names (can be customized per environment)
  _DATABASE_URL_SECRET_NAME: 'DATABASE_URL'
  _JWT_SECRET_NAME: 'JWT_SECRET'
  _JWT_REFRESH_SECRET_NAME: 'JWT_REFRESH_SECRET'
  _CSRF_TOKEN_SECRET_NAME: 'CSRF_TOKEN_SECRET'
  _RESEND_API_KEY_SECRET_NAME: 'RESEND_API_KEY'
  
  # Secret versions
  _DATABASE_URL_SECRET_VERSION: '1'
  _JWT_SECRET_VERSION: '1'
  _JWT_REFRESH_SECRET_VERSION: '1'
  _CSRF_TOKEN_SECRET_VERSION: '1'
  _RESEND_API_KEY_SECRET_VERSION: 'latest'
  
  # Email settings
  _EMAIL_FROM: 'noreply@nekoya.co.jp'
  _EMAIL_FROM_NAME: 'MyCats Pro'
  
  # Additional deploy flags (optional)
  _BACKEND_DEPLOY_FLAGS: ''
  _FRONTEND_DEPLOY_FLAGS: ''

options:
  logging: CLOUD_LOGGING_ONLY
