/**
 * Pedigreesテーブルのbreedリレーションで利用する品種マスターデータ。
 * 元データ: 猫種データUTF8Ver.csv（ヘッダー: キー, 種類名称）
 * 本ファイルではヘッダーを code / name にリネームし、全レコード (0-112) を保持する。
 */

export interface BreedMasterRecord {
  code: number;
  name: string;
}

export const BREED_MASTER_DATA: ReadonlyArray<BreedMasterRecord> = [
  { code: 0, name: "" },
  { code: 1, name: "Abyssinian" },
  { code: 2, name: "American Curl(LH)" },
  { code: 3, name: "American Curl(SH)" },
  { code: 4, name: "American Curl(LH.SE)" },
  { code: 5, name: "American Curl(SH.SE)" },
  { code: 6, name: "American Shorthair" },
  { code: 7, name: "American Wirehair" },
  { code: 8, name: "Balinese" },
  { code: 9, name: "Bengal" },
  { code: 10, name: "Birman" },
  { code: 11, name: "Bombay" },
  { code: 12, name: "British Shorthair" },
  { code: 13, name: "Burmese" },
  { code: 14, name: "Chartreux" },
  { code: 15, name: "Colorpoint Shorthair" },
  { code: 16, name: "Cornish Rex" },
  { code: 17, name: "Cymic" },
  { code: 18, name: "Devon Rex" },
  { code: 19, name: "Egyptian Mau" },
  { code: 20, name: "Exotic" },
  { code: 21, name: "Havana Brown" },
  { code: 22, name: "House Hold Pet" },
  { code: 23, name: "Japanese Bobtail" },
  { code: 24, name: "Javanese" },
  { code: 25, name: "Korat" },
  { code: 26, name: "Maine Coon" },
  { code: 27, name: "Manx" },
  { code: 28, name: "Munchkin (SH)" },
  { code: 29, name: "Norwegian Forest Cat" },
  { code: 30, name: "Ocicat" },
  { code: 31, name: "Oriental Longhair" },
  { code: 32, name: "Oriental Shorthair" },
  { code: 33, name: "Persian" },
  { code: 34, name: "Persian (HIMALAYAN)" },
  { code: 35, name: "Persian (C.P.C)" },
  { code: 36, name: "Ragdoll" },
  { code: 37, name: "Russian Blue" },
  { code: 38, name: "Scottish Fold (LH)" },
  { code: 39, name: "Scottish Fold (SH)" },
  { code: 40, name: "Scottish Fold(LH.SE)" },
  { code: 41, name: "Scottish Fold(SH.SE)" },
  { code: 42, name: "Snowshoe" },
  { code: 43, name: "Siamese" },
  { code: 44, name: "Selkirk Rex (SH)" },
  { code: 45, name: "Singapura" },
  { code: 46, name: "Somali" },
  { code: 47, name: "Sphynx" },
  { code: 48, name: "Tonkinese" },
  { code: 49, name: "Turkish Angora" },
  { code: 50, name: "Turkish Van" },
  { code: 51, name: "Wild Cat" },
  { code: 52, name: "Sugar Fold" },
  { code: 53, name: "Domestic Cat" },
  { code: 54, name: "European Burmese" },
  { code: 55, name: "Russian Blue (AOC)" },
  { code: 56, name: "Munchkin (SH.NL)" },
  { code: 57, name: "Munchkin (LH)" },
  { code: 58, name: "Exotic Longhair" },
  { code: 59, name: "Ragamuffin" },
  { code: 60, name: "American Curl" },
  { code: 61, name: "Scottish Fold" },
  { code: 62, name: "La Perm (LH)" },
  { code: 63, name: "La Perm (SH)" },
  { code: 64, name: "La Perm (LH.ST)" },
  { code: 65, name: "La Perm (SH.ST)" },
  { code: 66, name: "Munchkin (LH.NL)" },
  { code: 67, name: "Siberian" },
  { code: 68, name: "British Longhair" },
  { code: 69, name: "Domestic Cat (LH)" },
  { code: 70, name: "White (Albino)" },
  { code: 71, name: "Balinese-(Javanese)" },
  { code: 72, name: "Thai" },
  { code: 73, name: "Skookum" },
  { code: 74, name: "Selkirk Rex (LH)" },
  { code: 75, name: "Selkirk Rex (SH.ST)" },
  { code: 76, name: "Selkirk Rex (LH.ST)" },
  { code: 77, name: "American Curl (SWH)" },
  { code: 78, name: "American Curl (LWH)" },
  { code: 79, name: "Canadian Lop (SH)" },
  { code: 80, name: "Canadian Lop (LH)" },
  { code: 81, name: "Canadian Lop (SH.SE)" },
  { code: 82, name: "Canadian Lop (LH.SE)" },
  { code: 83, name: "Lamkin (SH)" },
  { code: 84, name: "Lamkin (LH)" },
  { code: 85, name: "Lamkin (SH.ST)" },
  { code: 86, name: "Lamkin (LH.ST)" },
  { code: 87, name: "Lamkin (SH.NL)" },
  { code: 88, name: "Lamkin (LH.NL)" },
  { code: 89, name: "Lamkin (SH.ST.NL)" },
  { code: 90, name: "Lamkin (LH.ST.NL)" },
  { code: 91, name: "Minuet(SH)" },
  { code: 92, name: "Minuet(LH)" },
  { code: 93, name: "Minuet(SH.NL)" },
  { code: 94, name: "Minuet(LH.NL)" },
  { code: 95, name: "Skookum (SH)" },
  { code: 96, name: "Skookum (LH)" },
  { code: 97, name: "Skookum (SH.NL)" },
  { code: 98, name: "Skookum (LH.NL)" },
  { code: 99, name: "Skookum (SH.ST)" },
  { code: 100, name: "Skookum (LH.ST)" },
  { code: 101, name: "Kinkaro (SH)" },
  { code: 102, name: "Kinkaro (LH)" },
  { code: 103, name: "Kinkaro (SH.SE)" },
  { code: 104, name: "Kinkaro (LH.SE)" },
  { code: 105, name: "Kinkaro (SH.NL)" },
  { code: 106, name: "Kinkaro (LH.NL)" },
  { code: 107, name: "Kinkaro (SH.SE.NL)" },
  { code: 108, name: "Kinkaro (LH.SE.NL)" },
  { code: 109, name: "ｱｷ" },
  { code: 110, name: "Bengal(A.O.C)" },
  { code: 111, name: "Jenetta" },
  { code: 112, name: "Toyger" },
];

const BREED_MASTER_MAP_ENTRIES = BREED_MASTER_DATA.map((record) => [record.code, record] as const);

export const BREED_MASTER_MAP: ReadonlyMap<number, BreedMasterRecord> = new Map(
  BREED_MASTER_MAP_ENTRIES,
);

export const findBreedByCode = (code: number): BreedMasterRecord | undefined =>
  BREED_MASTER_MAP.get(code);
